version: '3'
services:
  reports:
    image: reports-1.0-prod
    ports:
      - 80:80
    volumes:
      - ./reports:/var/www/html
    environment:
      DB_HOST: db
      DB_NAME: reports
      DB_USER: reports
      DB_PASSWORD: reports
    depends_on:
      - db
    networks:
      - app-network
  quiz:
    image: quiz-1.0-prod
    ports:
      - 81:80
    volumes:
      - ./quiz:/var/www/html
    environment:
      DB_HOST: db
      DB_NAME: quiz
      DB_USER: quiz
      DB_PASSWORD: quiz
    depends_on:
      - db
    networks:
      - app-network
  sms:
    image: sms-1.0-prod
    ports:
      - 82:80
    volumes:
      - ./sms:/var/www/html
    environment:
      DB_HOST: db
      DB_NAME: sms
      DB_USER: sms
      DB_PASSWORD: sms
    depends_on:
      - db
    networks:
      - app-network
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: phpmyadmin
      MYSQL_USER: phpmyadmin
      MYSQL_PASSWORD: phpmyadmin
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    depends_on:
      - db
    networks:
      - app-network
volumes:
  db_data:
networks:
  app-network:
    driver: bridge
